"""add reply_type

Revision ID: 1466588f9f9e
Revises: 07a4be41ef6e
Create Date: 2017-05-26 09:15:17.573000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1466588f9f9e'
down_revision = '07a4be41ef6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recomments', sa.Column('reply_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recomments', 'reply_type')
    # ### end Alembic commands ###
