"""add delete

Revision ID: 41537b73ed50
Revises: 54438a47b8b9
Create Date: 2017-06-19 12:15:35.431000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41537b73ed50'
down_revision = '54438a47b8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_delete', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('sendto_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sendto_delete')
    op.drop_column('messages', 'author_delete')
    # ### end Alembic commands ###
