"""add img

Revision ID: 487b255a18d4
Revises: 41537b73ed50
Create Date: 2017-06-21 13:33:47.544000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487b255a18d4'
down_revision = '41537b73ed50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'body_html')
    # ### end Alembic commands ###
