"""add at

Revision ID: c2e3d2066279
Revises: 2b9ef9b3bc19
Create Date: 2017-06-30 16:28:30.798000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e3d2066279'
down_revision = '2b9ef9b3bc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atusers', sa.Column('recomment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'atusers', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key(None, 'atusers', 'recomments', ['recomment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atusers', type_='foreignkey')
    op.drop_constraint(None, 'atusers', type_='foreignkey')
    op.drop_column('atusers', 'recomment_id')
    # ### end Alembic commands ###
