"""add no login

Revision ID: eef7d51d8826
Revises: 52aaf4f9745b
Create Date: 2017-07-12 11:27:59.064000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef7d51d8826'
down_revision = '52aaf4f9745b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allowlogin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allowlogin')
    # ### end Alembic commands ###
